### PR TITLE
Moved logic from template to php

### PR DESCRIPTION
**Pull request by madc**
Simplified the localeswitcher template.

Fixes: #30 
Refs: #14

### CODE REVIEW

**Comment by SahAssar** [comment]
Hmm, two things I'm thinking of w/r this:

1. It does not fetch/use the localized slugs from the db, which is a problem if one has `translate_slugs` turned on (which is the default) and have records with translated slugs since any record with translated slugs will 404 when clicking on a link to another language.

2. If one want's to add classes but keep the default _localeswitcher template that is hard with this patch (you'd need to do `{{localeswitcher('@bolt/frontend/_localeswitcher.twig', 'my_class_here')}}`) since php (IIRC) only uses default arguments if they are not passed, not if they are null, and therefore it needs a check inside the function or it will not work. For example doing `{{localeswitcher(null, 'my_class_here')}}` outputs nothing since the `$template` param will be `null`, not `'@bolt/frontend/_localeswitcher.twig'`. We could move to use named arguments, which would solve this nicely while keeping the code clean.

**Comment by madc** [comment]
You are again right. I updated the PR, so it gets the translated slug, if necessary.

As for 2): I'm not familiar with named arguments in php. As a quick solution, I changed the order of the arguments (first classes, then template), which makes sense anyway, as one will more often add classes as change the template. Correct me, if you feel differently about this.

**Comment by SahAssar** [comment]
LGTM, we'll do the named arguments thing in a future version

I'll update the readme for the switch of arguments :)

**Comment by SahAssar** [comment]
Oh, and the only reason classes was second was that we only used to have on arg (the template), which does not make sense to think about since we are breaking BC anyway :)

**Pull request merged**
