### PR TITLE
Some minor changes / cleanup.

### PR DESCRIPTION
**Pull request by bobdenotter**
Mostly stuff that appeared when working with `debug_error_level: -1`.

### CODE REVIEW

**Comment by SahAssar** [comment]
Thanks! :+1:

**Comment by EzeRangel** [comment]
When I try to save and return to listing it also drops the same warning in 06c901c. 

This is the line - [https://github.com/AnimalDesign/bolt-translate/blob/master/src/EventListener/StorageListener.php#L170](https://github.com/AnimalDesign/bolt-translate/blob/master/src/EventListener/StorageListener.php#L170)

**Comment by SahAssar** [comment]
Ah, @EzeRangel That's is unrelated to this one... Hold on a sec and I'll fix.

**Comment by SahAssar** [comment]
@EzeRangel Should now be fixed by 091c06b

Sorry, I assumed you were talking about the issue fixed by 851f05c when you mentioned this in slack.

**Comment by EzeRangel** [comment]
@SahAssar No problem :)

**Pull request merged**
