### PR TITLE
Don't throw exceptions in Bolt 3.2 with null routes

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by GawainLynch** [comment]
@bobdenotter this is the problem killing YoPro

**Comment by GawainLynch** [comment]
@SahAssar If this is good with you, could we kindly request a 4.0.1 tag today?

**Comment by SahAssar** [comment]
Thanks! Will tag a new release today :)

**Comment by GawainLynch** [comment]
Legendary mate, thank you!

**Pull request merged**
