### PR TITLE
Make readme more clear on the templatefields

### PR DESCRIPTION
**Pull request by lenvanessen**
[Prefix your PR title with [WIP], if it's a 'work in progress', or if you're looking for feedback before merging.]

A brief description of the Pull Request goes here.

Fixes: #1555 (please refer to an existing issue number, that this PR fixes)

### CODE REVIEW

**Comment by SahAssar** [comment]
Wouldn't this contradict the readme by making the templatefields translatable if one of the templatefields has is_translateable set?

**Comment by lenvanessen** [comment]
Yes! But if you look at the code, the actual procedure contradicts itself, because it doesn't check if one of the templatefields itself has is_translateable set, just if the select template field does.

PR incoming to fix that!

**Comment by SahAssar** [comment]
Well, the point is that setting any of the templatefields as `is_translateable` was thought to create the confusion that you could set some of the templatefields as translatable and some not, so my idea was to treat that option on the templateselect field as basically setting all templatefields as translateable.

**Comment by lenvanessen** [comment]
Well in that case we best leave the the inner-workings as is, but I read past this and made the assumption that it worked the same way as the other fields, hence the change to readme to highlight it a bit more

**Comment by SahAssar** [comment]
Merged the readme update via 10a40d0 :)

**Pull request closed without merging**
