### PR TITLE
First draft of 3.0 version

### PR DESCRIPTION
**Pull request by SahAssar**
This changes a lot of things about the extension, and also fixes a number of things like automatic route configuration (will add option to turn that off), require translated slugs (will add option to turn that off), liveedit and preview capability, and will hopefully have better compatibility with other extensions since they can use their own hydrate/persist functions (completely untested though).

It removes the need to use a custom content class or change the routing since those are overridden by the extension.

Lots of testing needed before releasing I think, but this should be a start to get us going.

If merged all new 2.X versions of the extension will need to be tagged from the bolt-2 branch I have setup.

Also, keep in mind that this is not compatible with latest stable due to bolt/bolt#5518 not having landed yet... It will only work with 3.0-dev or master until the next 3.0 minor is released.

Tests aren't there yet, but will come.

### CODE REVIEW

**Comment by SahAssar** [comment]
@madc since this is pretty much a rewrite/reboot of what we got I'm guessing that you want to sign off on it before merging, I'd be happy to hear any reservations you might have about it or the approach taken.

**Comment by madc** [comment]
Yes. Ähm. **This is awesome.** I had a quick look and you didn't really keep much of my code. But i like what you did!

Thing is, I'll start the first client project using Bolt 3 on Monday and it will use translate. I'm able to provide proper feedback by then, but don't want to delay this release. So I'd suggest that, if you're confidant with the code, go ahead and merge it. I feel more like a beta tester at the moment anyway.

Btw, I'm totally OK, if you want to put something like "SahAssar and [Contributors](https://github.com/AnimalDesign/bolt-translate/graphs/contributors)" in the About section of the readme.

**Comment by SahAssar** [comment]
@madc Thanks! I'll merge it in after I've patched up a few things that are a bit untested (like templatefields and extension fieldtypes). I'm looking forward to hearing your feedback on it!

Btw, for anyone testing this you should know that setting repeaters as translatable won't currently work because of bolt/bolt/issues/5533, but should work as soon as that is fixed.

**Comment by SahAssar** [comment]
Merging this in since a few of the sharper edges are fixed and so I can test with a "proper" install from the extension store (as opposed to a local install).

**Pull request merged**
