### PR TITLE
Fix homepage redirect and _locale on 404's

### PR DESCRIPTION
**Pull request by peterverraedt**
* Removed default _locale in routing. Instead, extended url_generator to make sure _locale is always available as a parameter (for 404's). Fixes: #47
* Use `reset($config->getLocales());` instead of `current` to get the first entry.
* Fixed typo in code.

### CODE REVIEW

**Comment by SahAssar** [comment]
Hey, sorry I was working on this at the same time as you... Since I want to keep the overrides to a minimum I decided to go another way on this, setting the homepageredirect to a higher priority and keeping the default but with much stricter requirements on all routes... Does that work for you too? See #49

**Comment by peterverraedt** [comment]
Putting the homepageredirect first was also my first thought, and it works, but only up to a certain level. The problem is that the url_generator will still give `/` if one requests the url of the homepage for the default locale, which implies that the menu item of the homepage will never be active when visiting the homepage in the default locale.

Moreover, if we want to use the `Accept-Language` header at some point, including at 404 responses, we would need a dynamic default value for _locale, which is impossible, or too early, to specify in routing.

**Comment by SahAssar** [comment]
It seems to generate a correct homepage url for me, `/en/` on a menuitem set to `path: homepage` (there's a trailing slash, but that I can fix in the menubuilder).

The `url_generator` solution only works on url's generated by bolt, right? So there are existing links to a site they will still get the 500 WSOD?

**Comment by peterverraedt** [comment]
Oh, right, if one uses `path: homepage`, it works correctly. I am using `route: homepage` instead, which has the behaviour I described above. Using `path('homepage')` in a theme would give the same.

**Comment by SahAssar** [comment]
Ah, I see, in that case your way seems better, thanks for being patient with me :)

By the way, I still think we should probably keep the requirements in the routing though, are you okay with that?

**Comment by peterverraedt** [comment]
The requirements in the routing are certainly useful, I also think we should keep them. I would probably have suggested it later :). Only keep in mind that this breaks the usage of the locale id [here](https://github.com/SahAssar/bolt-translate/blob/master/src/TranslateExtension.php#L119-L121). I am not sure whether supporting those urls is still necessary (for the previews?).

**Pull request merged**
