### PR TITLE
Adding "flag" icons for visibility, and a widget for the overview pages.

### PR DESCRIPTION
**Pull request by bobdenotter**
Screenshots: 

screen shot 2017-02-07 at 15 55 52

--------

screen shot 2017-02-07 at 15 55 36

---------

screen shot 2017-02-07 at 14 54 05

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hold off on merging, for now.. I'm going to replace the `.png` icons with SVG's.

**Comment by bobdenotter** [comment]
Should be GTG now. 

@SahAssar Please optimize the SVG's before tagging. I bet there's quite a bit to be gained, there.

**Comment by madc** [comment]
Looks great! Would be great to have the widget somewhere in the header, but it seems there is no widget position for that yet?

**Comment by bobdenotter** [comment]
> Looks great! Would be great to have the widget somewhere in the header, but it seems there is no widget position for that yet?

Nope, on the overview page, at the top of the aside is the best we can do. 

> Also it might be a good idea to have a config option to show/hide the widget on the dashboard.

I'm not sure i agree. It only shows on overview pages when applicable. I can't readily think of a situation where it wouldn't be good to show it. If we don't show it, there's no indication of the current language at all.

**Comment by SahAssar** [comment]
Alright, merging in, and will PR the optimized ones later. We can also tweak the specifics later if we want.

**Comment by SahAssar** [comment]
@bobdenotter btw, #105 for the optimized ones.

**Pull request merged**
